/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.ctgu.adapter;

import android.widget.BaseAdapter;
import android.annotation.SuppressLint;
import android.content.Context;

import java.util.ArrayList;
import java.util.List;

import com.ctgu.ctguhelp.R;
import com.ctgu.ctguhelp.R.color;
import com.ctgu.model.Book;
import com.ctgu.model.Course;
import com.ctgu.model.Course1;

import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

public class CourseAdapter extends BaseAdapter {
	private Context context;
	private List<Course> courseList;

	public CourseAdapter(Context context) {
		courseList = new ArrayList<Course>();
		this.context = context;
	}

	public void addItems(ArrayList<Course> newItems) {
		if ((newItems == null) || (newItems.size() <= 0)) {
			return;
		}
		for (int i = 0; i < newItems.size(); i++) {
			courseList.add(newItems.get(i));
		}

		notifyDataSetChanged();
	}
	public void clear() {
		courseList.clear();
		notifyDataSetChanged();
	}
	public int getCount() {
		return courseList.size();
	}

	public Object getItem(int position) {
		return courseList.get(position);
	}

	public long getItemId(int position) {
		return position;
	}

	@SuppressLint("NewApi")
	public View getView(int position, View convertView, ViewGroup parent) {
		Course info = (Course) courseList.get(position);
		View view = View.inflate(context, R.layout.course_item, null);
		TextView tv_course = (TextView) view.findViewById(R.id.tv_course);
		TextView tv_score = (TextView) view.findViewById(R.id.tv_score);
		TextView tv_pingjiaoOperate = (TextView) view.findViewById(R.id.tv_pingjiaoOperate);
		tv_course.setText(info.getCourse());
		tv_score.setText(info.getTeacher());
		if (info.getPingjiaoOperateId().isEmpty()) {
			tv_pingjiaoOperate.setTextColor(color.gray);
			tv_pingjiaoOperate.setText("已经评教");
		}
		// if (info.getCondition().isEmpty()) {
		// tv_condition.setTextColor(color.gray);
		// tv_condition.setText("已经评教");
		// }
		return view;
	}
}
