/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.ctgu.adapter;

import android.widget.BaseAdapter;
import android.content.Context;
import java.util.ArrayList;

import com.ctgu.ctguhelp.R;
import com.ctgu.model.Lost_Find_Message;

import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

public class Lost_Find_Adapter extends BaseAdapter {
    private Context conext;
    private ArrayList<Lost_Find_Message> lost_find_message;
    
    public Lost_Find_Adapter(Context conext, ArrayList<Lost_Find_Message> lost_find_message) {
        this.lost_find_message = lost_find_message;
        this.conext = conext;
    }
    
    public int getCount() {
        return lost_find_message.size();
    }
    
    public Object getItem(int position) {
        return lost_find_message.get(position);
    }
    
    public long getItemId(int position) {
        return position;
    }
    public View getView(int position, View convertView, ViewGroup parent) {
        Lost_Find_Message message = (Lost_Find_Message)lost_find_message.get(position);
        View v = View.inflate(conext, R.layout.lost_find_list_item, null);
        TextView lost_find_goods_name = (TextView)v.findViewById(R.id.lost_find_goods_name);
        TextView lost_find_goods_describe = (TextView)v.findViewById(R.id.lost_find_goods_describe);
        TextView lost_find_goods_time = (TextView)v.findViewById(R.id.lost_find_goods_time);
        lost_find_goods_name.setText(message.getTitle());
        lost_find_goods_describe.setText(message.getKeyword());
        lost_find_goods_time.setText(message.getTime());
        return v;
    }
}
