/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.ctgu.adapter;

import android.widget.BaseAdapter;
import android.widget.Button;
import android.widget.LinearLayout;
import android.content.Context;
import java.util.ArrayList;

import com.ctgu.adapter.ReviewAdapter.onClick;
import com.ctgu.ctguhelp.R;
import com.ctgu.model.Message;
import com.ctgu.model.MyMessages;
import com.ctgu.model.Review;
import com.ctgu.util.ExpressionUtil;
import com.example.login.Message_Board_Test;
import com.example.login.MyMessage;
import com.example.login.TranionMyMessage;

import android.text.SpannableString;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.TextView;

public class TranionMyMessageAdapter extends BaseAdapter {
	private int index;
	private Context conext;
	private ArrayList<MyMessages> messageArr;
	private MyMessages m;
	private TranionMyMessage my;

	public TranionMyMessageAdapter(Context conext, TranionMyMessage my) {
		messageArr = new ArrayList<MyMessages>();
		this.conext = conext;
		this.my = my;

	}

	public void addItems(ArrayList<MyMessages> newItems) {
		if ((newItems == null) || (newItems.size() <= 0)) {
			return;
		}
		for (int i = 0; i < newItems.size(); i++) {
			messageArr.add(newItems.get(i));
		}

		notifyDataSetChanged();
	}

	public void clear() {
		messageArr.clear();
		notifyDataSetChanged();
	}

	public int getCount() {
		return messageArr.size();
	}

	public Object getItem(int position) {
		return messageArr.get(position);
	}

	public long getItemId(int position) {
		return position;
	}

	public View getView(int position, View convertView, ViewGroup parent) {
		this.index = position;
		View v = View.inflate(conext, R.layout.review_item, null);
		this.m = messageArr.get(position);
		LinearLayout conview = (LinearLayout) v.findViewById(R.id.conview);
		TextView review_user = (TextView) v.findViewById(R.id.review_user);
		TextView review_time = (TextView) v.findViewById(R.id.review_time);
		TextView review_content = (TextView) v.findViewById(R.id.review_content);
		TextView TVreview = (TextView) v.findViewById(R.id.review);
		review_user.setText("      " + m.getDiscuss() + "回复" + m.getUser());
		review_time.setText(m.getTime());
		String str =m.getContent();
		String zhengze = "f0[0-9]{2}|f10[0-7]";									//正则表达式，用来判断消息内是否有表情
		try {
			SpannableString spannableString = ExpressionUtil.getExpressionString(conext, str, zhengze);
			review_content.setText(spannableString);
		} catch (NumberFormatException e) {
			e.printStackTrace();
		} 

		conview.setOnClickListener(new onClick());
		TVreview.setOnClickListener(new onClick());
		return v;
	}

	class onClick implements OnClickListener {
		final int p = index;
		@Override
		public void onClick(View v) {
			MyMessages r = (MyMessages) getItem(p);
			my.onItem(v.getId(), p, r);
		}
	}

}
