/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.example.login;

import com.ctgu.base.BaseUiAuth;
import android.widget.ListView;
import android.os.Bundle;

public class About_Us extends BaseUiAuth {
    ListView list_message_board;
    
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(0x7f030000);
    }
}
