/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.example.login;

import com.ctgu.base.BaseUiAuth;
import org.apache.http.HttpResponse;
import android.widget.LinearLayout;
import com.ctgu.util.MyHttp;
import android.view.View;
import com.ctgu.serve.MyServe;
import android.content.Intent;
import android.os.Bundle;
import android.view.MotionEvent;

public class Exit extends BaseUiAuth {
	HttpResponse httpResponse;
	private LinearLayout layout;
	MyHttp myhttp;

	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(0x7f030004);
		layout = (LinearLayout) findViewById(0x7f0a000d);
	}

	public boolean onTouchEvent(MotionEvent event) {
		finish();
		return true;
	}

	public void exitbutton1(View v) {
		finish();
	}

	public void exitbutton0(View v) {
		my_serve.setCtgu_login(false);
		doTaskAsync(0, "Login.aspx?xttc=1");
		Intent my_serve_intent = new Intent(this, MyServe.class);
		stopService(my_serve_intent);
		finish();
	}
}
