/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.example.login;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;

import org.apache.http.Header;

import com.ctgu.adapter.Library_Adapter;
import com.ctgu.base.BaseActivity;
import com.ctgu.base.BaseTask;
import com.ctgu.base.BaseUiAuth;
import com.ctgu.base.C;
import com.ctgu.ctguhelp.R;
import com.ctgu.model.Book;
import com.ctgu.model.MBookDetails;

import com.ctgu.util.AsyncHttp;
import com.ctgu.util.IO;
import com.ctgu.util.XmlToString;
import com.loopj.android.http.AsyncHttpResponseHandler;
import com.loopj.android.http.RequestParams;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.AbsListView;
import android.widget.AbsListView.OnScrollListener;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ListView;
import android.widget.TextView;

import android.annotation.SuppressLint;
import android.app.AlertDialog;

public class LibraryIndex extends BaseActivity {

	EditText keyWord;

	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.libraryindex);
		keyWord = (EditText) findViewById(R.id.keyWord);

		Button search = (Button) findViewById(R.id.search);

		search.setOnClickListener(new OnClickListener() {

			@SuppressLint("NewApi")
			@Override
			public void onClick(View v) {
				String key = keyWord.getText().toString().trim();
				if (!key.isEmpty()) {
					Bundle b = new Bundle();
					b.putString("key", key);
					post(key);
					forward_not_finish(Library.class, b);
				} else {
					toast("关键字不能为空");
				}
			}
		});
	}

	public void post(String key) {
		RequestParams params = new RequestParams();
		params.put("keyword", key);
		params.put("user", user.getMy_userName());
		AsyncHttp.Post(C.api.postLibraryKey, params, new AsyncHttpResponseHandler() {

			@Override
			public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
				// TODO Auto-generated method stub

			}

			@Override
			public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error) {
				// TODO Auto-generated method stub

			}
		});
	}
}
