/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.example.login;

import android.view.View;
import android.view.View.OnClickListener;
import android.widget.EditText;
import android.text.Editable;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import com.ctgu.model.Lost_Find_Message;
import com.ctgu.util.IO;
import com.ctgu.util.NewTaskPool;
import com.ctgu.base.BaseTask;
import com.ctgu.base.C;

import android.widget.RadioGroup;
import android.widget.RadioButton;
import com.ctgu.base.BaseActivity;
import com.ctgu.ctguhelp.R;

import android.widget.Button;
import android.os.Bundle;

public class Lost_Find_Edit extends BaseActivity {
	private RadioButton find;
	private RadioButton lost;
	private EditText lost_find_edit_goods;
	private EditText lost_find_edit_keyword;
	private EditText lost_find_edit_name;
	private EditText lost_find_edit_other;
	private EditText lost_find_edit_phone;
	private EditText lost_find_edit_place;
	private Button lost_find_edit_publish;
	private EditText lost_find_edit_qq, lost_find_edit_time;
	private RadioGroup lost_find_type;
	private int type = 0;

	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.lost_find_edit);
		View_Init();
	}

	private void View_Init() {
		lost_find_edit_goods = (EditText) findViewById(R.id.lost_find_edit_goods);
		lost_find_edit_keyword = (EditText) findViewById(R.id.lost_find_edit_keyword);
		lost_find_edit_name = (EditText) findViewById(R.id.lost_find_edit_name);
		lost_find_edit_qq = (EditText) findViewById(R.id.lost_find_edit_qq);
		lost_find_edit_other = (EditText) findViewById(R.id.lost_find_edit_other);
		lost_find_edit_phone = (EditText) findViewById(R.id.lost_find_edit_phone);
		lost_find_edit_place = (EditText) findViewById(R.id.lost_find_edit_place);
		lost_find_edit_time = (EditText) findViewById(R.id.lost_find_edit_time);
		lost = (RadioButton) findViewById(R.id.lost);
		find = (RadioButton) findViewById(R.id.find);
		lost_find_type = (RadioGroup) findViewById(R.id.lost_find_type);
		lost_find_type.setOnCheckedChangeListener(new OnCheckedChangeListenerImp());
		lost_find_edit_publish = (Button) findViewById(R.id.lost_find_edit_publish);
		lost_find_edit_publish.setOnClickListener(new Message_Board_Edit_On_click());
	}

	class OnCheckedChangeListenerImp implements RadioGroup.OnCheckedChangeListener {

		public void onCheckedChanged(RadioGroup group, int checkedId) {
			if (lost.getId() == checkedId) {
				type = 1;
			} else if (find.getId() == checkedId) {
				type = 2;
			}
		}
	}

	class Message_Board_Edit_On_click implements OnClickListener {

		public void onClick(View v) {
			if (type == 0) {
				toast("请选择失物信息或者招领信息");
			} else {
				if (type == 1) {
					type = 29;
				} else if (type == 2) {
					type = 30;
				}
				pd.show();
				HashMap<String, String> taskArgs = new HashMap<String, String>();
				taskArgs.put("cid", String.valueOf(type));
				taskArgs.put("title", lost_find_edit_goods.getText().toString().trim());
				taskArgs.put("keyword", lost_find_edit_keyword.getText().toString().trim());
				taskArgs.put("diu_place", lost_find_edit_place.getText().toString().trim());
				taskArgs.put("phone", lost_find_edit_phone.getText().toString().trim());
				taskArgs.put("name", lost_find_edit_name.getText().toString().trim());
				taskArgs.put("qq", lost_find_edit_qq.getText().toString().trim());
				taskArgs.put("other", lost_find_edit_other.getText().toString().trim());
				taskArgs.put("time", lost_find_edit_time.getText().toString().trim());
				task_pool_get_lost_find.addTask(C.task.addGoods, C.api.addGoods, taskArgs, new BaseTask() {
					public void onComplete(InputStream inputStream) {
						String data = IO.inputSreamToString(inputStream);
						sendMessage(BaseTask.TASK_COMPLETE, getId(), data);
					}

					public void onError(String error) {
						sendMessage(BaseTask.NETWORK_ERROR, getId(), null);
					}
				}, 0);
			}
		}
	}

	public void onTaskComplete(int taskId, Object message) {
		switch (taskId) {
		case C.task.addGoods: {
		if(pd.isShowing()){
			pd.dismiss();
		}
			toast((String) message);
			break;
		}
		}
	}
}
