/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.example.login;

import android.view.Gravity;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.view.Window;
import android.widget.AdapterView;
import android.widget.EditText;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.SimpleAdapter;
import android.text.Editable;
import android.text.Spannable;
import android.text.SpannableString;
import android.text.style.ImageSpan;

import java.io.InputStream;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.ctgu.util.IO;
import com.ctgu.base.BaseTask;
import com.ctgu.base.BaseUiAuth;
import com.ctgu.base.C;
import com.ctgu.ctguhelp.R;

import android.widget.Button;
import android.widget.AdapterView.OnItemClickListener;
import android.annotation.SuppressLint;
import android.app.AlertDialog;
import android.app.AlertDialog.Builder;
import android.app.Dialog;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.os.Bundle;

public class Message_Board_Edit extends BaseUiAuth {
	private EditText message_board_edit_content;
	private Button message_board_edit_publish;

	private int[] imageIds = new int[107];
	private Builder builder;
	private ImageView expression;

	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.message_board_edit);
		View_Init();
	}

	private void View_Init() {
		message_board_edit_content = (EditText) findViewById(R.id.message_board_edit_content);
		message_board_edit_publish = (Button) findViewById(R.id.message_board_edit_publish);
		expression = (ImageView) findViewById(R.id.team_singlechat_id_expression);
		message_board_edit_publish.setOnClickListener(new On_click());
		expression.setOnClickListener(new On_click());

	}

	class On_click implements OnClickListener {

		@SuppressLint("NewApi")
		public void onClick(View v) {
			switch (v.getId()) {
			case R.id.message_board_edit_publish:
				if (!message_board_edit_content.getText().toString().trim().isEmpty()) {
					HashMap<String, String> taskArgs = new HashMap<String, String>();
					taskArgs.put("user", user.getMy_userName());
					taskArgs.put("content", message_board_edit_content.getText().toString().trim());
					pd.show();
					taskPool_ctguHelp.addTask(C.task.send_message, C.api.send_message, taskArgs, new BaseTask() {

						@Override
						public void onComplete(InputStream inputStream) {
							String data = IO.inputSreamToString(inputStream);
							sendMessage(BaseTask.TASK_COMPLETE, C.task.send_message, data);
						}

						@Override
						public void onError(String error) {
							sendMessage(BaseTask.NETWORK_ERROR, C.task.send_message, null);
						}
					}, 0);
				} else {
					toast("内容不能为空");
				}
				break;
			case R.id.team_singlechat_id_expression:
				createExpressionDialog();
				break;

			}

		}
	}

	public void onTaskComplete(int taskId, Object message) {
		switch (taskId) {
		case C.task.send_message:
			if (pd.isShowing()) {
				pd.dismiss();
			}
			toast((String) message);
			finish();

		}
	}

	/**
	 * 创建一个表情选择对话框
	 */
	@SuppressWarnings("unused")
	private void createExpressionDialog() {
		builder = new AlertDialog.Builder(Message_Board_Edit.this);
		GridView gridView = createGridView();
		builder.setView(gridView);
		final AlertDialog bb = builder.show();
		gridView.setOnItemClickListener(new OnItemClickListener() {
			@Override
			public void onItemClick(AdapterView<?> arg0, View arg1, int arg2, long arg3) {

				int resId = imageIds[arg2 % imageIds.length];
				ImageSpan imageSpan = new ImageSpan(Message_Board_Edit.this, resId, 10);
				String str = null;
				if (arg2 < 10) {
					str = "f00" + arg2;
				} else if (arg2 < 100) {
					str = "f0" + arg2;
				} else {
					str = "f" + arg2;
				}
				SpannableString spannableString = new SpannableString(str);
				spannableString.setSpan(imageSpan, 0, 4, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
				message_board_edit_content.append(spannableString);
				bb.dismiss();
			}
		});
	}

	private GridView createGridView() {
		final GridView view = new GridView(this);
		List<Map<String, Object>> listItems = new ArrayList<Map<String, Object>>();
		// 生成107个表情的id，封装
		for (int i = 0; i < 107; i++) {
			try {
				if (i < 10) {
					Field field = R.drawable.class.getDeclaredField("f00" + i);
					int resourceId = Integer.parseInt(field.get(null).toString());
					imageIds[i] = resourceId;
				} else if (i < 100) {
					Field field = R.drawable.class.getDeclaredField("f0" + i);
					int resourceId = Integer.parseInt(field.get(null).toString());
					imageIds[i] = resourceId;
				} else {
					Field field = R.drawable.class.getDeclaredField("f" + i);
					int resourceId = Integer.parseInt(field.get(null).toString());
					imageIds[i] = resourceId;
				}
			} catch (NumberFormatException e) {
				e.printStackTrace();
			} catch (SecurityException e) {
				e.printStackTrace();
			} catch (IllegalArgumentException e) {
				e.printStackTrace();
			} catch (NoSuchFieldException e) {
				e.printStackTrace();
			} catch (IllegalAccessException e) {
				e.printStackTrace();
			}
			Map<String, Object> listItem = new HashMap<String, Object>();
			listItem.put("image", imageIds[i]);
			listItems.add(listItem);
		}

		SimpleAdapter simpleAdapter = new SimpleAdapter(this, listItems, R.layout.team_layout_single_expression_cell, new String[] { "image" }, new int[] { R.id.image });
		view.setAdapter(simpleAdapter);
		view.setNumColumns(6);
		view.setBackgroundColor(Color.rgb(214, 211, 214));
		view.setHorizontalSpacing(1);
		view.setVerticalSpacing(1);
		view.setLayoutParams(new LayoutParams(LayoutParams.FILL_PARENT, LayoutParams.WRAP_CONTENT));
		view.setGravity(Gravity.CENTER);
		return view;
	}
}
