/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.example.login;

import android.view.View;
import android.view.View.OnClickListener;
import android.widget.EditText;
import android.text.Editable;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import com.ctgu.model.Message;
import com.ctgu.serve.MyServe;
import com.ctgu.util.NewTaskPool;
import com.ctgu.base.BaseTask;
import com.ctgu.base.BaseUiAuth;
import com.ctgu.base.C;
import com.ctgu.ctguhelp.R;
import com.ctgu.ctguhelp.R.color;

import android.widget.Button;
import android.annotation.SuppressLint;
import android.os.Bundle;
import android.widget.TextView;
import android.text.TextPaint;
import com.ctgu.util.IO;

public class UserLogin extends BaseUiAuth {
	Button bt_login;
	EditText my_user_number;
	EditText my_user_password;

	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		if (!user.getMy_userName().equals("")) {
			MyServe.setUserName(user.getMy_userName());
			forward(Index.class);
		}
		setContentView(R.layout.user_login);
		my_user_number = (EditText) findViewById(R.id.login_my_user_number);
		my_user_password = (EditText) findViewById(R.id.login_my_user_password);
		bt_login = (Button) findViewById(R.id.bt_login);
		TextView register = (TextView) findViewById(R.id.register);
		TextView lost_password = (TextView) findViewById(R.id.lost_password);
		register.getPaint().setFlags(color.red);
		lost_password.getPaint().setFlags(color.red);
		register.setOnClickListener(new OnClick());
		lost_password.setOnClickListener(new OnClick());
		bt_login.setOnClickListener(new OnClick());
	}

	class OnClick implements OnClickListener {

		public void onClick(View v) {

			switch (v.getId()) {
			case R.id.bt_login:
				loginMethod();
				break;
			case R.id.register:
				forward(Register.class);
				break;
			case R.id.lost_password:
				toast("请联系三大小助手新浪微博或者QQ");
				break;
			}

		}

		@SuppressLint("NewApi")
		private void loginMethod() {
			HashMap<String, String> taskArgs = new HashMap<String, String>();
			String number = my_user_number.getText().toString().trim();
			String password = my_user_password.getText().toString().trim();
			if (!(number.isEmpty() || password.isEmpty())) {
				taskArgs.put("my_user_number", number);
				taskArgs.put("my_user_password", password);
				pd.show();
				taskPool_ctguHelp.addTask(C.task.userLogin, C.api.userLogin, taskArgs, new BaseTask() {

					@Override
					public void onComplete(InputStream inputStream) {

						String data = IO.inputSreamToString(inputStream);
						sendMessage(BaseTask.TASK_COMPLETE, C.task.userLogin, data);
					}

					@Override
					public void onError(String error) {
						sendMessage(BaseTask.NETWORK_ERROR, C.task.userLogin, null);
					}

				}, 0);
			} else {
				toast("用户名或者密码为空");
			}
		}
	}

	public void onTaskComplete(int taskId, Object message) {
		String result = (String) message;
		String[] ResultArray = result.split("&");
		switch (taskId) {
		case C.task.userLogin: {
			if (pd.isShowing()) {
				pd.dismiss();
			}
			if (ResultArray[0].equals("1")) {
				String user_name = ResultArray[1];
				IO.saveToPackage(this, user_name, "my_user.txt");
				MyServe.setUserName(user.getMy_userName());
				my_serve.setCtguhelp_login(true);
				toast("登陆成功");

				forward(Index.class);

				return;
			}
			if (ResultArray[0].equals("0")) {
				toast("用户名或者密码错误");
				return;
			}
			if (ResultArray[0].equals("-1")) {
				toast("用户名并不存在");
				break;
			}
		}
		}
	}
}
