/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.ctgu.base;

import com.ctgu.ctguhelp.R;
import com.example.login.Config;
import com.example.login.Message_Board_Test;
import com.example.login.My_Menu;
import com.example.login.My_course_table;
import com.example.login.Recreation;

import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import android.view.View;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View.OnClickListener;

public class BaseUiAuth extends BaseActivity {
	RelativeLayout bTabBlog;
	RelativeLayout bTabConf;
	RelativeLayout bTabHome;
	RelativeLayout bTabWrite;
	ImageView IMbTabHome, IMbTabBlog, IMbTabConf, IMbTabWrite;
	static BaseUiAuth instance = null;

	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		instance = this;
		
	}

	public void onStart() {
		super.onStart();
		bindMainTab();
		
	}

	public boolean onCreateOptionsMenu(Menu menu) {
		super.onCreateOptionsMenu(menu);
		return true;
	}

	public boolean onOptionsItemSelected(MenuItem item) {
		item.getItemId();
		return super.onOptionsItemSelected(item);
	}

	private void bindMainTab() {
		bTabHome = (RelativeLayout) findViewById(R.id.main_tab_1);
		bTabBlog = (RelativeLayout) findViewById(R.id.main_tab_2);
		bTabConf = (RelativeLayout) findViewById(R.id.main_tab_3);
		bTabWrite = (RelativeLayout) findViewById(R.id.main_tab_4);

	
		
		IMbTabHome = (ImageView) findViewById(R.id.main_tab_1_image);
		IMbTabBlog = (ImageView) findViewById(R.id.main_tab_2_image);
		IMbTabConf = (ImageView) findViewById(R.id.main_tab_3_image);
		IMbTabWrite = (ImageView) findViewById(R.id.main_tab_4_image);

		if ((bTabHome != null) && (bTabBlog != null) && (bTabConf != null)) {
			OnClickListener mOnClickListener = new View.OnClickListener() {

				public void onClick(View v) {
					switch (v.getId()) {
					case R.id.main_tab_1:
						forward(My_Menu.class);
						break;
					case R.id.main_tab_2:
						forward(Recreation.class);
						break;
					case R.id.main_tab_3:
						forward(My_course_table.class);
						break;
					case R.id.main_tab_4:
						forward(Config.class);
						break;
					case R.id.main_tab_1_image:
						forward(My_Menu.class);
						break;
					case R.id.main_tab_2_image:
						forward(Recreation.class);
						break;
					case R.id.main_tab_3_image:
						forward(My_course_table.class);
						break;
					case R.id.main_tab_4_image:
						forward(Config.class);
						break;

					}
				}
			};

			IMbTabHome.setOnClickListener(mOnClickListener);
			IMbTabBlog.setOnClickListener(mOnClickListener);
			IMbTabConf.setOnClickListener(mOnClickListener);
			IMbTabWrite.setOnClickListener(mOnClickListener);

			bTabHome.setOnClickListener(mOnClickListener);
			bTabBlog.setOnClickListener(mOnClickListener);
			bTabConf.setOnClickListener(mOnClickListener);
			bTabWrite.setOnClickListener(mOnClickListener);
		}

	}

	
}
