/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.ctgu.model;

public class Message implements Comparable {
	private String content;
	private int id;
	private String time;
	private String user;
	private int read, good, sort,discuss;

	

	public Message(String content, int id, String time, String user, int read, int good, int sort, int discuss) {
		super();
		this.content = content;
		this.id = id;
		this.time = time;
		this.user = user;
		this.read = read;
		this.good = good;
		this.sort = sort;
		this.discuss = discuss;
	}

	public int getDiscuss() {
		return discuss;
	}

	public void setDiscuss(int discuss) {
		this.discuss = discuss;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public int getRead() {
		return read;
	}

	public void setRead(int read) {
		this.read = read;
	}

	public int getGood() {
		return good;
	}

	public void setGood(int good) {
		this.good = good;
	}

	public int getSort() {
		return sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}

	public int compareTo(Message another) {
		if (id > another.id) {
			return -1;
		}
		return 1;
	}

	

	@Override
	public String toString() {
		return "Message [content=" + content + ", id=" + id + ", time=" + time + ", user=" + user + ", read=" + read + ", good=" + good + ", sort=" + sort + ", discuss=" + discuss + "]";
	}

	@Override
	public int compareTo(Object arg0) {
		// TODO Auto-generated method stub
		return 0;
	}
}
