/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.ctgu.model;


public class MyUser {
    private String my_user_name;
    private String tag;
    
    public MyUser() {
    }
    
    public String getTag() {
        return tag;
    }
    
    public void setTag(String tag) {
        tag = tag;
    }
    
    public String getMy_user_name() {
        return my_user_name;
    }
    
    public void setMy_user_name(String my_user_name) {
        my_user_name = my_user_name;
    }
}
