/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.ctgu.model;

import android.content.Context;
import java.io.File;

import com.ctgu.util.IO;

public class User {
    private Context context;
    private String my_userName;
    private String name;
    private String password;
    private String user;
    private String userNumber;
    private String[] userResult;
    
    public User(Context context) {
        this.context = context;
        File user_file = new File(this.context.getCacheDir(), "user.txt");
        if(user_file.exists()) {
            user = IO.readFile(user_file);
            userResult = user.split("&");
            userNumber = userResult[0];
            password = userResult[1];
            name = userResult[2];
        }
        File my_user_file = new File(this.context.getCacheDir(), "my_user.txt");
        if(my_user_file.exists()) {
        	my_userName = IO.readFile(my_user_file).toString().trim();
        }else{
        	my_userName="";
        }
    }
    
    public User(String userNumber, String password, String name) {
       this.userNumber = userNumber;
       this.password = password;
       this.name = name;
    }
    
    public String getUserNumber() {
        return userNumber;
    }
    
    public void setUserNumber(String userNumber) {
    	this.userNumber = userNumber;
    }
    
    public String getPassword() {
        return password;
    }
    
    public void setPassword(String password) {
    	this.password = password;
    }
    
    public String getName() {
        return name;
    }
    
    public void setName(String name) {
    	this.name = name;
    }
    
    public String getUser() {
        return user;
    }
    
    public void setUser(String user) {
    	this.user = user;
    }
    
    public String[] getUserResult() {
        return userResult;
    }
    
    public void setUserResult(String[] userResult) {
    	this.userResult = userResult;
    }
    
    
    /**
     * 返回小助手的用户昵称；
     * @return
     */
    public String getMy_userName() {
        return my_userName;
    }
    
    public void setMy_userName(String my_userName) {
    	this.my_userName = my_userName;
    }
    
  
}
