/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.ctgu.util;

import org.apache.http.client.HttpClient;
import org.apache.http.HttpResponse;
import java.io.InputStream;
import android.util.Log;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpUriRequest;
import org.apache.http.StatusLine;
import org.apache.http.Header;
import org.apache.http.HttpEntity;
import java.util.List;
import org.apache.http.NameValuePair;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.client.entity.UrlEncodedFormEntity;

public class MyHttpPost {
    HttpClient client;
    HttpResponse httpResponse;
    
    public InputStream Get(String path) {
        Log.i("myhttp", "httpGET提交开始");
        InputStream is = null;
        HttpGet httpGet = new HttpGet(path);
        try {
            httpResponse = client.execute(httpGet);
            Log.i("myhttp", "httpGET提交中");
            if(httpResponse.getStatusLine().getStatusCode() == 0xc8) {
                Header[] header = httpResponse.getAllHeaders();
                is = httpResponse.getEntity().getContent();
                Log.i("myhttp", "httpGET成功");
                return is;
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
        return is;
    }
    
    public InputStream Post(String path, List<NameValuePair> parmenters) {
        Log.i("myhttp", "httpPOST提交开始");
        Log.i("提交地址", path);
        InputStream is = null;
        try {
            HttpPost httpPost = new HttpPost(path);
            httpPost.setEntity(new UrlEncodedFormEntity(parmenters, "UTF-8"));
            httpResponse = client.execute(httpPost);
            Log.i("myhttp", "httpPOST提交中");
            if(httpResponse.getStatusLine().getStatusCode() == 0xc8) {
                is = httpResponse.getEntity().getContent();
                Log.i("myhttp", "httpPOST成功");
                return is;
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
        return is;
    }
}
